In [ ]:
pip install opencv-python

In [ ]:
pip install numpy

In [11]:
!pip install opencv-python opencv-contrib-python numpy

In [ ]:
import cv2 # Import the OpenCV library to enable computer vision
import numpy as np # Import the NumPy scientific computing library
import glob # Used to get retrieve files that have a specified pattern

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
!ls '/content/drive/MyDrive/UET/Kì 2 - năm 3 - 2020_2021/Computer Vision'


Camera_calibration


In [15]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [17]:

def calibrate(dirpath, prefix, image_format, square_size, width=9, height=6):
    """ Apply camera calibration operation for images in the given directory path. """
    # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(8,6,0)
    objp = np.zeros((height*width, 3), np.float32)
    objp[:, :2] = np.mgrid[0:width, 0:height].T.reshape(-1, 2)
    
    #objp is our chessboard matrix.
    objp = objp * square_size

    # Arrays to store object points and image points from all the images.
    objpoints = []  # 3d point in real world space
    imgpoints = []  # 2d points in image plane.

    if dirpath[-1:] == '/':
        dirpath = dirpath[:-1]

    images = glob.glob(dirpath+'/' + prefix + '*.' + image_format)

    for fname in images:
        img = cv2.imread(fname)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Find the chess board corners
        ret, corners = cv2.findChessboardCorners(gray, (width, height), None)

        # If found, add object points, image points (after refining them)
        if ret:
            objpoints.append(objp)

            corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
            imgpoints.append(corners2)

            # Draw and display the corners
            img = cv2.drawChessboardCorners(img, (width, height), corners2, ret)

    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

    return [ret, mtx, dist, rvecs, tvecs]

In [19]:
image_format ='jpg'
square_size = 0.025
image_dir = '/content/drive/MyDrive/UET/Kì 2 - năm 3 - 2020_2021/Computer Vision/Camera_calibration/Image'
prefix = "IMG"

In [21]:
ret, mtx, dist, rvecs, tvecs = calibrate(image_dir, prefix, image_format, 0.025)

In [24]:
mtx
# the camera matrix

array([[3.04689491e+03, 0.00000000e+00, 1.52112164e+03],
       [0.00000000e+00, 3.05732054e+03, 1.96020550e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [23]:
rvecs
#rotation vec

[array([[-0.13997347],
        [ 0.45756157],
        [-1.50791789]]), array([[-0.10707978],
        [-0.34233599],
        [-1.4378056 ]]), array([[ 0.01774344],
        [-0.25245553],
        [-1.52413827]]), array([[-0.48803795],
        [ 0.23906502],
        [-1.55948639]]), array([[ 0.16127504],
        [ 0.27072939],
        [-1.5743463 ]]), array([[-0.15720026],
        [-0.02007885],
        [-1.56973886]]), array([[-0.14191326],
        [ 0.45761956],
        [-1.50811721]]), array([[-0.13967407],
        [ 0.46202984],
        [-1.50860214]]), array([[-0.13895964],
        [ 0.46074719],
        [-1.50819078]]), array([[-0.35832816],
        [-0.26177794],
        [-1.53984953]]), array([[-0.14012284],
        [ 0.46305338],
        [-1.50781518]]), array([[-0.6266415 ],
        [-0.22099672],
        [-1.11942711]]), array([[-0.61734325],
        [-0.21575674],
        [-1.14576488]]), array([[-0.29593839],
        [-0.26504618],
        [-3.02645195]]), array([[-0.53429783

In [25]:
tvecs
#translation vectors

[array([[-0.08407724],
        [ 0.14178085],
        [ 0.31176316]]), array([[-0.05506529],
        [ 0.04735284],
        [ 0.22618135]]), array([[-0.04063001],
        [ 0.08741167],
        [ 0.20284807]]), array([[-0.08082539],
        [ 0.11247213],
        [ 0.25620276]]), array([[-0.0652957 ],
        [ 0.14559728],
        [ 0.25912956]]), array([[-0.07287773],
        [ 0.099303  ],
        [ 0.23851358]]), array([[-0.08372124],
        [ 0.14236143],
        [ 0.31082731]]), array([[-0.08417917],
        [ 0.14087542],
        [ 0.31313439]]), array([[-0.08377003],
        [ 0.14133397],
        [ 0.31221111]]), array([[-0.07664213],
        [ 0.05909236],
        [ 0.1907257 ]]), array([[-0.08367116],
        [ 0.14109388],
        [ 0.31266992]]), array([[-0.10838034],
        [ 0.01427724],
        [ 0.29762145]]), array([[-0.1196953 ],
        [ 0.01264152],
        [ 0.29882553]]), array([[ 0.1270744 ],
        [-0.00982493],
        [ 0.24714431]]), array([[-0.04259958

In [26]:
type(tvecs)

list

In [37]:
import numpy as np

In [33]:
matrix_1 = mtx.dot(rvecs[0])
matrix_1

array([[-2.72021099e+03],
       [-1.55691655e+03],
       [-1.50791789e+00]])

In [40]:
matrix_2 = np.transpose(tvecs[0])
matrix_2

array([[-0.08407724,  0.14178085,  0.31176316]])

In [41]:
coordinate_room =  (matrix_1).dot(matrix_2) 
coordinate_room

array([[ 2.28707819e+02, -3.85673836e+02, -8.48061579e+02],
       [ 1.30901239e+02, -2.20740957e+02, -4.85389226e+02],
       [ 1.26781567e-01, -2.13793885e-01, -4.70113249e-01]])